### ISSUE TITLE
TypeError: must be real number, not NoneType in some indicators

### ISSUE THREAD

**Issue by quadramadery** [bitfinexcom/bfx-hf-indicators-py#5]
Acceleration, AccumulationDistribution, BollingerBands, ChaikinOsc, CoppockCurve, RVI, StochasticRSI are broken after changes in #2

It's because now `v()` returns `None` instead of `0` when buffer is not empty and those indicators pass `v()` results to `isfinite()` or do math on it which yields errors like:
- TypeError: must be real number, not NoneType and 
- TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

This could be fixed by either reverting `None` to `0` or adding guards against `None` before calling `isfinite`/doing math. Which one is better? Asking, because I don't quite understand the reason behind switching to `None` as original issue seemed to revolve around issue with `<=`.

This was caught by unit tests proposed in PR #3 

```
======================================================================
ERROR: test_add (tests.Acceleration_test.AccelerationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qm/git/bfx-hf-indicators-py/tests/Acceleration_test.py", line 59, in test_add
    indicator.add(candles[i]['close'])
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/acceleration.py", line 49, in add
    if not isfinite(roc):
TypeError: must be real number, not NoneType

======================================================================
ERROR: test_add (tests.AccumulationDistribution_test.AccumulationDistributionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qm/git/bfx-hf-indicators-py/tests/AccumulationDistribution_test.py", line 49, in test_add
    indicator.add(candles[i])
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/accumulation_distribution.py", line 42, in add
    if isfinite(prev):
TypeError: must be real number, not NoneType

======================================================================
ERROR: test_add (tests.BollingerBands_test.BollingerBandsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qm/git/bfx-hf-indicators-py/tests/BollingerBands_test.py", line 229, in test_add
    indicator.add(candles[i]['close'])
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/bbands.py", line 49, in add
    'top': middle + (self._m * stddev),
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

======================================================================
ERROR: test_add (tests.ChaikinOsc_test.ChaikinOscTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qm/git/bfx-hf-indicators-py/tests/ChaikinOsc_test.py", line 59, in test_add
    indicator.add(candles[i])
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/chaikin_oscillator.py", line 48, in add
    self._adl.add(candle)
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/accumulation_distribution.py", line 42, in add
    if isfinite(prev):
TypeError: must be real number, not NoneType

======================================================================
ERROR: test_add (tests.CoppockCurve_test.CoppockCurveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qm/git/bfx-hf-indicators-py/tests/CoppockCurve_test.py", line 73, in test_add
    indicator.add(candles[i]['close'])
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/coppock_curve.py", line 48, in add
    if not isfinite(short) or not isfinite(long):
TypeError: must be real number, not NoneType

======================================================================
ERROR: test_add (tests.RVI_test.RVITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qm/git/bfx-hf-indicators-py/tests/RVI_test.py", line 59, in test_add
    indicator.add(candles[i]['close'])
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/relative_volatility_index.py", line 70, in add
    if not isfinite(stddev):
TypeError: must be real number, not NoneType

======================================================================
ERROR: test_add (tests.StochasticRSI_test.StochasticRSITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qm/git/bfx-hf-indicators-py/tests/StochasticRSI_test.py", line 191, in test_add
    indicator.add(candles[i]['close'])
  File "/home/qm/git/bfx-hf-indicators-py/bfxhfindicators/stochastic_rsi.py", line 70, in add
    if not isfinite(rsi):
TypeError: must be real number, not NoneType

```

**Comment by renegadeofunk** [comment]
Nothing after almost 2 years?

**Comment by kezdawggy** [comment]
yes it is disappointing
